#!/usr/bin/env sh

readonly CLIENT=/usr/bin/emacsclient
readonly DAEMON=/usr/bin/emacs
readonly LOG="${HOME}/.local/var/log/emacs"

main()
{
	# Disable proxies because it kills spacemacs for a minute or 5
	$(proxy-toggle off)

	# Start daemon if needed
	start_daemon

	# Start emacs in the cwd if no args provided
	if [ "$#" -lt 1 ]
	then
		$CLIENT -c .
		return
	fi

	# Start emacs with the given arguments
	$CLIENT "$@"
}

start_daemon()
{
	# Check if emacs is already running as daemon
	if pgrep -fail emacs | grep -q 'emacs \-\-daemon'
	then
		return 1
	fi

	logdir=$(dirname "${LOG}")

	# Make sure the log directory exists
	if [ ! -d "${logdir}" ]
	then
		mkdir -p "${logdir}" || echo "Could not create ${LOG}" && exit 1
	fi

	unset logdir

	$DAEMON --daemon 2>> "${LOG}"
	return 0
}

main "$@"
