#!/usr/bin/env perl
# Author:  Patrick Spek <p.spek@tyil.nl>
# License: BSD 3-clause license

use strict;
use warnings;

if ($ARGV[0] eq 'foreground') {
	print "\033[38;5;$ARGV[1]m$ARGV[2]\033[m"
}

if ($ARGV[0] eq 'background') {
	print "\033[48;5;$ARGV[1]m$ARGV[2]\033[m"
}

if ($ARGV[0] eq 'both') {
	print "\033[38;5;$ARGV[1];48;5;$ARGV[2]m$ARGV[3]\033[m"
}

