#!/usr/bin/env sh

WALLDIR=~/pictures/wallpapers/1920x1080

if [ -z "$1" ]; then
	TIMEOUT=0
else
	TIMEOUT=$1
fi

if [[ $TIMEOUT -eq 0 ]]; then
	find "${WALLDIR}" -type f -print0 | shuf -n1 -z | xargs -0 feh --bg-fill
else
	while true; do
		find "${WALLDIR}" -type f -print0 | shuf -n1 -z | xargs -0 feh --bg-fill
		sleep "${TIMEOUT}"
	done
fi

