#!/usr/bin/env sh
# Author:  Patrick Spek <p.spek@tyil.nl>
# License: BSD 3-clause license

location="."
fmod="644"
dmod="755"

# set the directory if not given
if [ -n "$1" ]; then
	location=$1
fi

# set file permissions if not given
if [ -n "$2" ]; then
	fmod=$2
fi

# set the directory permissions if not given
if [ -n "$3" ]; then
	dmod=$3
fi

# apply permissions to directories
find "${location}" -type d -print0 | xargs -0 chmod 0${dmod}

# apply permissions to files
find "${location}" -type f -print0 | xargs -0 chmod 0${fmod}

