#!/usr/bin/env sh
# Author:  Patrick Spek <p.spek@tyil.nl>
# License: BSD 3-clause license

wmname LG3D && _JAVA_OPTIONS="-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel -Dswing.crossplatformlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel" $@
