#!/usr/bin/env sh

# If an argument is given, check if we have an xinitrc for that
if [ -n "$1" ]; then
	if [ ! -f ~/.xinit/${1}.rc ]; then
		echo "no valid config for $1"
		exit
	fi

	# Remove the old config
	if [ -f ~/.xinitrc ]; then
		rm ~/.xinitrc
	fi

	# Create the new config
	cat ~/.xinit/xinitrc ~/.xinit/$1.rc > ~/.xinitrc

	# Append local-machine configuration if it exists
	if [ -f "~/.config/x/initrc.post" ]
	then
		cat ~/.config/x/xinitrc.post >> ~/.xinitrc
	fi
fi

# Make sure the xinitrc exists, just in case
if [ ! -f ~/.xinitrc ]; then
	echo "no xinitrc"
	exit
fi

# start the X session
startx
