{+block +handle-as-image}
.goatse.ca
.goatse.cx
.goat.cx
.oralse.ca
.oralse.cx
.1girl1pitcher.org
.1guy1cock.com
.1man1jar.org
.1man2needles.com
.1priest1nun.com
.1priest1nun.net
.2girls1cup.cc
.2girls1cup-free.com
.2girls1cup.nl
.2girls1cup.ws
.2girls1finger.org
.2guys1stump.org
.3guys1hammer.ws
.4girlsfingerpaint.org
.bagslap.com
.ballsack.org
.bestshockers.com
.bluewaffle.biz
.bottleguy.com
.bowlgirl.com
.cadaver.org
.clownsong.com
.copyright-reform.info
.cshacks.partycat.us
.cyberscat.com
.dadparty.com
.detroithardcore.com
.donotwatch.org
.dontwatch.us
.eelsoup.net
.fruitlauncher.com
.fuck.org
.funnelchair.com
.goatse.bz
.goatsegirl.org
.goatse.ru
.hai2u.com
.homewares.org
.howtotroll.org
.japscat.org
.jiztini.com
.junecleeland.com
.kids-in-sandbox.com
.kidsinsandbox.info
.lemonparty.biz
.lemonparty.org
.lolhello.com
.lolshock.com
.loltrain.com
.meatspin.biz
.meatspin.com
.merryholidays.org
.milkfountain.com
.mudfall.com
.mudmonster.org
.nimp.org
.nobrain.dk
.nutabuse.com
.octopusgirl.com
.on.nimp.org
.painolympics.info
.painolympics.org
.phonejapan.com
.pressurespot.com
.prolapseman.com
.punishtube.com
.scrollbelow.com
.selfpwn.org
.sourmath.com
.strawpoii.me
.suckdude.com
.thatsjustgay.com
.thatsphucked.com
.theexgirlfriends.com
.thehomo.org
.themacuser.org
.thepounder.com
.tubgirl.me
.tubgirl.org
.turdgasm.com
.vomitgirl.org
.walkthedinosaur.com
.whipcrack.org
.wormgush.com
.xvideoslive.com
.y8.com
.youaresogay.com
.ypmate.com
.zentastic.com
1girl1pitcher.com
1girl1pitcher.org
1guy1cock.com
1man1jar.org
1man2needles.com
1priest1nun.com
1priest1nun.net
2girls1cup.cc
2girls1cup.com
2girls1cup-free.com
2girls1cup.nl
2girls1cup.ws
2girls1finger.com
2girls1finger.org
2guys1stump.org
3guys1hammer.ws
4girlsfingerpaint.com
4girlsfingerpaint.org
bagslap.com
ballsack.org
bestshockers.com
bluewaffle.biz
bottleguy.com
bowlgirl.com
cadaver.org
clownsong.com
copyright-reform.info
cshacks.partycat.us
cyberscat.com
dadparty.com
detroithardcore.com
donotwatch.org
dontwatch.us
eelsoup.net
fruitlauncher.com
fuck.org
funnelchair.com
goatse.bz
goatsegirl.org
goatse.ru
hai2u.com
homewares.org
howtotroll.org
japscat.org
jarsquatter.com
jiztini.com
junecleeland.com
kids-in-sandbox.com
kidsinsandbox.info
lemonparty.biz
lemonparty.org
lolhello.com
lolshock.com
loltrain.com
meatspin.biz
meatspin.com
merryholidays.org
milkfountain.com
mudfall.com
mudmonster.org
nimp.org
nobrain.dk
nutabuse.com
octopusgirl.com
on.nimp.org
painolympics.info
painolympics.org
phonejapan.com
pressurespot.com
prolapseman.com
scrollbelow.com
selfpwn.org
sexitnow.com
sourmath.com
strawpoii.me
suckdude.com
thatsjustgay.com
thatsphucked.com
thehomo.org
themacuser.org
thepounder.com
tubgirl.me
tubgirl.org
turdgasm.com
vomitgirl.org
walkthedinosaur.com
whipcrack.org
wormgush.com
youaresogay.com
zentastic.com
