" enable pathogen for plugins
execute pathogen#infect()
execute pathogen#helptags()

" enable fancy features
filetype plugin indent on
syntax enable

let s:path = fnamemodify(resolve(expand('<sfile>:p')), ':h')

for f in split(globpath(s:path . "/functions", '*.vim'), '\n')
	exe "so " . f
endfor

" vim settings
set ai
set cuc
set cul
set fdm=syntax
set lcs=tab:>-,trail:~
set list
set lz
set nu
set rnu
set ru
set scrolloff=666
set si
set sm
set ut=500
set wig=*.swp,*.bak,*.pyc,*.class,*.jar,*.gif,*.png,*.jpg,.precomp
set wmnu

call SetCharLimit(79)
call SetIndent(3)

" add hotkeys
nmap <F6> :make<CR>

" set normal numbering in insert
au InsertEnter * :set nornu
au InsertLeave * :set rnu

" enable views by default
au BufWinLeave ?* mkview
au BufWinEnter ?* silent loadview

" sudo write
ca w!! w !sudo tee > /dev/null "%"

" Persistent undo
if has("persistent_undo")
	set undodir=~/.vim/undo
	set undolevels=1000
	set undofile
endif

ru theme.vim
ru leaderkeys.vim
ru plugins.vim
