#! /usr/bin/env sh

case "$1" in
	"hdmi")
		xrandr --output HDMI1 --auto
		;;
	"rerander")
		xrandr --output VGA1 --auto --above eDP1 --output HDMI1 --auto --left-of VGA1
		;;
	"vga")
		xrandr --output VGA1 --auto
		;;
	*)
		xrandr --output VGA1 --off --output HDMI1 --off
		;;
esac

