#!/usr/bin/env sh
# Author:  Patrick Spek <p.spek@tyil.nl>
# License: BSD 3-clause license

# this should fix sudo with aliases
alias sudo="sudo "

# musicplayer aliases {{{
alias ma="mpc add"
alias mh="ncmpcpp --host"
alias mp="mpc toggle > /dev/null"
# }}}

# tmux aliases {{{
alias t="tmux -2 -f ~/.config/tmux/conf -u"
# }}}

# virsh aliases {{{
alias v="virsh --connect qemu:///system"
alias vc="v console"
alias vl="v list --all"
alias vp="v suspend"
alias vr="v resume"
alias vs="v start"
# }}}

# other aliases {{{
alias :q="exit"
alias ag="ag --color-line-number '0;33' --color-match '1;31' --color-path '1;33' --smart-case"
alias bc="bc -i ~/.config/bcrc"
alias cpan6="perl6 -I ~/projects/scriptkitties/perl6-App-Cpan6/lib -I ~/projects/private/perl6-JSON-Fast/lib ~/projects/scriptkitties/perl6-App-Cpan6/bin/cpan6"
alias e="vim"
alias g="grep --color=always -i"
alias links-g="links -g" # Termite cant deal with it if its an argument
alias muttman="~/projects/rb/muttman/src/muttman"
alias p="ps -A -o pid,comm | grep -i"
alias rcopy="rsync --append-verify --info=ALL,PROGRESS -ar"
alias slideshow="feh -zsZ.D 5"
alias wifiman="wicd-curses"
alias parescan="pacmd unload-module module-udev-detect && pacmd load-module
module-udev-detect"
# }}}
