#!/usr/bin/env sh

hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1

# frames
hc set frame_border_active_color '#ff0000'
hc set frame_border_normal_color '#101010'
hc set frame_bg_normal_color     '#00ff00'
hc set frame_bg_active_color     '#0000ff'
hc set frame_border_width        0
hc set always_show_frame         1
hc set frame_bg_transparent      1
hc set frame_transparent_width   0
hc set frame_gap                 0
hc set frame_padding             0

# windows
hc set window_gap                   8
hc set smart_window_surroundings    0
hc set smart_frame_surroundings     1
hc set mouse_recenter_gap           0
hc attr theme.active.color          '#5778c1'
hc attr theme.normal.color          '#393939'
hc attr theme.urgent.color          orange
hc attr theme.inner_width           1
hc attr theme.inner_color           black
hc attr theme.border_width          3
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width  1
hc attr theme.floating.outer_color  black
hc attr theme.active.inner_color    '#3E4A00'
hc attr theme.active.outer_color    '#3E4A00'
hc attr theme.background_color      '#141414'

